export const LOAD_USER  = 'LOAD_USER'
export const DRAW_LOAD_USER = 'DRAW_LOAD_USER'
export const SUCCESS_LOAD_USER = 'SUCCESS_LOAD_USER'
export const FAILED_LOAD_USER = 'FAILED_LOAD_USER'

export const ADD_USER  = 'ADD_USER'
export const DRAW_ADD_USER = 'DRAW_ADD_USER'
export const SUCCESS_ADD_USER = 'SUCCESS_ADD_USER'
export const FAILED_ADD_USER = 'FAILED_ADD_USER'

export const REMOVE_USER  = 'REMOVE_USER'
export const DRAW_REMOVE_USER = 'DRAW_REMOVE_USER'
export const SUCCESS_REMOVE_USER = 'SUCCESS_REMOVE_USER'
export const FAILED_REMOVE_USER = 'FAILED_REMOVE_USER'

export const RESEND_USER  = 'RESEND_USER'
export const DRAW_RESEND_USER = 'DRAW_RESEND_USER'
export const SUCCESS_RESEND_USER = 'SUCCESS_RESEND_USER'
export const FAILED_RESEND_USER = 'FAILED_RESEND_USER'